# -*- coding: utf-8 -*-
"""ConvertDataSetTo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IYydBOIODB0UxZl4lkU5urJNzK_TRsZF
"""

import pandas as pd

# Lee el archivo CSV de entrada
input_file = 'dataset_pairs.csv'  # Reemplaza con el nombre de tu archivo de entrada
output_file = 'dataset_guanaco.csv'  # Nombre del archivo de salida

# Carga el dataset
df = pd.read_csv(input_file)

# Genera el formato de salida
df['formatted_text'] = df.apply(lambda row: f"<s>[INST] {row['input_text']} [/INST] {row['target_text']} </s>", axis=1)

# Guarda el archivo en el nuevo formato
df[['formatted_text']].to_csv(output_file, index=False, header=False)

print(f"Archivo formateado guardado como {output_file}")

from google.colab import files

# Ejecuta esta línea para abrir el selector de archivos y subir desde tu computadora
uploaded = files.upload()

# Esto cargará el archivo y lo guardará en el sistema de archivos temporal de Colab
# Los archivos estarán disponibles en el diccionario uploaded usando el nombre como clave

from google.colab import files
files.download('dataset_guanaco.csv')  # Cambia 'dataset_squad.csv' si el nombre es diferente